export const SEARCH_LOCATION = 'SEARCH_LOCATION';
export const STORE_USERINFO = 'STORE_USERINFO';
export const ADD_REMINDER = 'ADD_REMINER';
export const UPDATE_REMINDER = 'UPDATE_REMINDER';
export const DELETE_REMINDER = 'DELETE_REMINDER';

// export const ADD_FRIEND = 'ADD_FRIEND';
// export const API_FAVORITES = 'API_FAVORITES';
// export const ADD_FAVORITE = 'ADD_FAVORITE';
// export const DELETE_FAVORITE = 'DELETE_FAVORITE';
// export const UPDATE_FAVORITES = 'UPDATE_FAVORITES';
